detail_link: https://t.me/online_violence/18
images:
- index_file/AsP9n6lVWg_d35.jpg
- index_file/POvFOyCURZ_746.jpg
- index_file/XDLZcNSS2X_cbe.jpg
offender: 轻尘
tags:
- 性骚扰
- 死亡威胁
- 辱骂
wechat_id: YS188816661999
