detail_link: https://t.me/online_violence/18
images:
- https://cdn1.telesco.pe/file/ktIJl81B5mX33TMfL12leQZ_Owm5aO4bck9JoyaDqHkKHaclJQQEsS6e-tdZIsokAbY_w3Xx32XLtNWKmPDeh0eDQlAkvGHujDJWGPJ1MULAF9Bj0ov4EoTmrN_9i82RMmgzC4pA-sEzZ02AT3lRRBrdgLgjGPc34mqhcsU0bpwaT2DfAAOQN9tEQg8YXATETOnaJdN9A0_78ohVvALxlyppTcOiqwsw-54tu1ptq5_Hf4m16qkxYmQqfYInbaa69Ofnfv63FWLxJIzgyQ6vP1EbQzadTobc1rHGow_bqjE8x1cPr_aA24BljTKbRcptyxIIwvEk-L0zWBURZCGWRQ.jpg
- https://cdn1.telesco.pe/file/FfTqzorJjAhRwmayrGfxJK8G3-BF-ymfvGPXKyWkUjGyNXMuZtiO9vFjp4LnnxwB6ImALzuUO2PWARTexAnv6rJ5sS7ShdhB3jQvjNeWFDyc6NbEZ9-D9CWACGrDgIy56KDm8uw_vFF2nCqyMD47t88LRwsEOJMLKUUih4uhSh18BkE9Av3YWK4uGswHTR_rYkuiGqMO2wJE2W4ksuETDojScl-ZuwK_7sSFniw4F5lm4UFgcBI3mMNsA2xaOo4_Rvkckt17waQVqXmoQxshH7cRe1TgyXiXOVZtIYci77GDu-_YDZWtcJ2NRapxyVway7XdNJPz80M6thjPPw6Dnw.jpg
- https://cdn1.telesco.pe/file/tmlbj-Nc8rpXl2OIG2Cb-LJb8CtxYtc6vmNhkxjo5hzY7j_eTJqHcWAWw6Yu4EAmJHZxGEtvbrd3IZWaWU9E1pSza9dlNu2507fCloaoQy_Rr2ojMPMfisKJA-7VDxdL6fidCdKq4HKEt0Sg-hXmSGzlc3TqnEONgks73eLr56a-0c_zYEaDp0HbInIlocAcAer80Ne_7SEJVR-jxr4Yh-Sa-v4zy8s_oQb-KimI10g8MwMfh3-IIrjDsf1wHp6_rfekcLKbJ_W2qkhT-94D-UAU-JTYpHxbMkgOO-tMA-rS03dmv2jiyMxcsWUluJmGL1GvhvlLysPmtFCg30YIeA.jpg
offender: 轻尘
tags:
- 性骚扰
- 死亡威胁
- 辱骂
wechat_id: YS188816661999
