detail_link: https://t.me/online_violence/18
images:
- https://cdn1.telesco.pe/file/Xim4i1HxTieI5B0dLdExBz4VNFD2a2Qn6dVT-6tXLUTFLFORPJEknt1J-rQiqZ3nGmcyzF2hDoOvnVybJPlCXCwGgjO5O9GRGqR93Nw3Gl_dIpM3ShJ1Jdst0JN_TuDUyOUyPqCEXHCaJTGeXNYfTgwB_Y0Zf1Znq2EEmAmm9oeBp57HXzuPmaE0Cmz368v-24NoNvt_bZsoveAeZ1Eb7keqg5ygupZ-MvRo6Ky6nst-RQsdGCOzhmrtoto8Kq44XX_nghysGT2GiRwvlCwS8ijszGO687rJycOQ6lHj8ZA43NfoGKSvrN8MHHEDYm3hBiKm-2_zDovPkKeWmHzhLA.jpg
- https://cdn1.telesco.pe/file/d_XjsDCkXTyi7b9cUIsb6ezb50MV9NuAwbrW12EHp2hPaWGLpP1blO9eWtUUP5bN_0CMI2TczSF47mHnbefF8lv1O7OqTBglZse79tJ3gUbxS4SxpGYdRa8c2O2TtgavqyTA-DUCabc3xmB7NJwhSbwBaH_KCWAdqIo139RE1wyz5oh6C4eKnkHKWgLxnmbPg05Lm57-Wx9yFGr_UyDfz-LQABL6k2btv8ZJz8t5WISH9hzFEAJ_-uTuRnxft5J2WmSiTh0zogyKtG6vX2JywgnN0R7TNs7d7HSFZc3oUKLVNlkmvTdEbi2u5c0laSiWwicvR2rLfIvbe3ayLmx7QA.jpg
- https://cdn1.telesco.pe/file/Hjgo1lJC6lQ8F9WM2PClHgq1plRtmt82u24pNDmCfMv1T6AJHFTzyAUMWvcb2SiayUk_JGz13whGVq-FoWVRhCH4YjuRxonWE0bqsitHniBp24igO5JuT84E0wEFjksUhd93I6JiHzro1zkcSn5KY5XidXfIgYptduHOtenlrri4SkoIhD1XH2m-XjwNBF0SBVi_00o3FX786vLnO1PywlMfLrk_tbG8yRKvO30X-j8LnQ3g4tIDUoW3JOvcCVJU4jqpkA03yvQ1LGs2wBuP7hcUowUr1aH_LxDaF_aBWG95UqDjS05NNvXjXfLBCq1UxUs3zLNNidk4jKjMO2vyVA.jpg
offender: 轻尘
tags:
- 性骚扰
- 死亡威胁
- 辱骂
wechat_id: YS188816661999
